# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app143', '0002_multiplebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAuthoeBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authoe', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
