# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app143', '0003_multiauthoebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users1', to=settings.AUTH_USER_MODEL),
        ),
    ]
