# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app143', '0004_auto_20170914_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('address', models.TextField()),
                ('mobileno', models.CharField(max_length=12)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
