# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app143', '0005_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiauthoebooks',
            name='authoe',
        ),
        migrations.AddField(
            model_name='multiauthoebooks',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
