# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app143', '0006_auto_20170918_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='l_name',
        ),
    ]
