# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app143', '0007_auto_20170918_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
