# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app143', '0009_auto_20171029_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('gender', models.BooleanField(choices=[(True, 'male'), (False, 'Female')])),
                ('mobileno', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='bookname',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app143.Students'),
        ),
    ]
